spring:
  application:
    name: 'football-standings-service'

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html